# -*- coding: utf-8 -*-
"""todolist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QAeLzsi8bvfj3EkqNpNvbkvkB5-8q-ba
"""

DOSYA_ADI = "gorevler.txt"

#dosyadan görevleri oku
def gorev_oku():
  gorevler =[]
  try:
    dosya= open(DOSYA_ADI, mode="r", encoding="utf-8")
    satirlar = dosya.readlines()
    # Her satırı strip ile temizleyip listeye ekle
    gorevler = [satir.strip() for satir in satirlar if satir.strip()]
    dosya.close()
  except FileNotFoundError:
        # Dosya yoksa başlatmak için boş liste döner
        pass
  except Exception as e:
        print(f"Dosya okuma hatası: {e}")
  return gorevler

#her yapılan değişikliği kaydet
def kaydet(gorevler):
  try:
    dosya = open(DOSYA_ADI, mode="w", encoding="utf-8")
    for gorev in gorevler:
      dosya.write(gorev + "\n")
    dosya.close()
  except Exception as e:
    print(f"Dosya yazma hatası: {e}")

#görevleri listele
def gorev_listele(gorevler):
  if not gorevler:
    print("\nMevcut bir görev yok.\n")
  else:
    print("\n Görev Listesi")
    for i, gorev in enumerate(gorevler, start=1):
      print(f"{i}. {gorev}")
    print()

#görev ekle
def gorev_ekle(gorevler):
  yeni_gorev=input("Yeni Görev: ").strip().capitalize()   #Eklenen görevin görünüm açısından estetik durması için baş harfi büyük yazdır
  if not yeni_gorev:
    print("Boş görev eklenemez!")
    return
  gorevler.append(yeni_gorev)
  kaydet(gorevler)  # Liste güncellendiği için hemen kaydet
  print("Görev başarıyla eklendi.")

#görev düzenle
def gorev_duzenle(gorevler):
  gorev_listele(gorevler)
  if not gorevler:
    return
  try:
    duzenlenecek_gorev=int(input("Düzenlenecek görev numarası: "))
    if 1 <= duzenlenecek_gorev <= len(gorevler):
      yeni_gorev=input("Yeni görev: ").strip().capitalize()
      if not yeni_gorev:
        print("Boş görev eklenemez!")
        return
      gorevler[duzenlenecek_gorev-1]=yeni_gorev
      kaydet(gorevler)
      print("Görev başarıyla güncellendi.")
    else:
      print("Geçersiz görev numarası!")
  except ValueError:
    print("Lütfen sadece sayı girin!")

#görev sil
def gorev_sil(gorevler):
  gorev_listele(gorevler)
  if not gorevler:
    return
  try:
    secim = int(input("Silinecek görev numarası: "))
    if 1 <= secim <= len(gorevler):
            silinen = gorevler.pop(secim - 1)
            kaydet(gorevler)
            print(f"'{silinen}' silindi.")
    else:
            print("Geçersiz numara!")
  except ValueError:
    print("Sayı girilmelidir!")


#ana menü
def ana_menu():
  gorevler=gorev_oku()
  while True:
    print("\n*** Görev Yönetim Uygulaması ***")
    print("1. Görevleri Listele")
    print("2. Yeni Görev Ekle")
    print("3. Görev Düzenle")
    print("4. Görev Sil")
    print("5. Çıkış")

    try:
        secim = int(input("Seçiminiz: "))
        if secim < 1 or secim > 5:
            print("Geçersiz seçim.")
            continue
    except ValueError:
        print("Lütfen sadece sayı girin.")
        continue

    if secim == 1:
        try:
            gorev_listele(gorevler)
        except Exception as e:
            print(f"Hata: {e}")
    elif secim == 2:
        try:
            gorev_ekle(gorevler)
        except Exception as e:
            print(f"Hata: {e}")
    elif secim == 3:
        try:
            gorev_duzenle(gorevler)
        except Exception as e:
            print(f"Hata: {e}")
    elif secim == 4:
        try:
            gorev_sil(gorevler)
        except Exception as e:
            print(f"Hata: {e}")
    elif secim == 5:
        print("Çıkış yapılıyor...")
        break

#uygulamayı başlat
ana_menu()